### ISSUE TITLE
Question about Chrono Trigger checksum

### ISSUE THREAD

**Issue by mcred** [mikearnos/snessum#1]
As an experiment, I'm working on an editor for SNES9x Chrono Trigger battery saves in GoLang. Your checksum code is really helpful, I think I understand what is going on, but I am not too familiar with C. Can you let me know if I describe what is happening here accurately?

```
void fix_chrono_trigger(){
	for (slot = 0; slot < 3; slot++) {
		checksum = 0;
		for (i = 0x9FE / 2; i >= 0; i--) {
			if (checksum > 0xFFFF) {
				checksum -= 0xFFFF;
			}
			checksum += sram_memw[i + slot * 0xA00 / 2];
		}
		checksum &= 0XFFFF;
		sram_memw[0x1FF0 / 2 + slot] = checksum;
	}
	printf("Chrono Trigger sram checksums fixed (3)\n");
}
```

```
for (slot = 0; slot < 3; slot++) {
```
Loop through each save slot, can be 0, 1 or 2. This is used as a multiplier in lower steps to offset the range. 

```
for (i = 0x9FE / 2; i >= 0; i--) {
	if (checksum > 0xFFFF) {
		checksum -= 0xFFFF;
	}
	checksum += sram_memw[i + slot * 0xA00 / 2];
}
```
For each save slot, loop over every other Byte and get their value as 16bit in reverse order (Little Endian). Instead of loading every Byte and getting their values as 8bit. If the total incremented checksum goes over a 16bit value, reset to zero and keep adding up. 

```
checksum &= 0XFFFF;
```
I think this is making a bitwise cast to ensure that the checksum is written as hex in the file. 

```
sram_memw[0x1FF0 / 2 + slot] = checksum;
```
I believe this is writing the calculate checksum to the correct location in the save file. 

Does this seem like an accurate understanding?

**Comment by mikearnos** [comment]
Hey Derek, thanks for your interest in my code. The structure of the sram seems to be 3 blocks of data, each being 0xA00 bytes long. At the end of the sram, there's a sort of header with some values

0x1FE0 = 0x00 - 0x02 which file is highlighted
0x1FE2 = 0xFF "New Game+" enabled (any value other than 0 enables)
0x1FE1 = ?
0x1FF8, 0x1FFA, 0x1FFC = 0xE41B signature word identifying a save files
0x1FF0, 0x1FF2, 0x1FF4 = checksum word

For clarity, here's the original assembly code to calculate the checksum.

```
LDY #$09FE                  ;Y = start with word at location 0x09FE
LDA #$0000                  ;A = 0000 (reset 16 bit checksum amount)
CLC                         ;Carry bit = 0
ADC ($00),y[$30:69FE]       ;add word at offset Y plus carry bit (last word is at at $30:6000)
DEY                         ;decrease byte pointer twice
DEY                         ;since we're counting words
BPL $FA    [$FBFB]          ;loop if positive (>=0)
```

So yes, 3 save slots, and it's counting all the bytes as little-endian words. So the data 0x12 0x34 0x56 0x78 would add up to 0xAC68. My weird notation of `sram_memw[0x1FF0 / 2 + slot]` is so I can use the familiar byte file location of 0x1FF0 instead of the word location of 0xFF8.

Now you can do the checksum of the save slots and it will work sometimes, but it will be off by 1 sometimes if you just reset it to zero. That's because the algorithm uses `ADC` (Add with carry). So if the checksum ever goes above 0xFFFF, it resets to zero yes, but the carry flag gets set to 1. The carry flag gets added next time and reset to zero. So that's why I `checksum -= 0xFFFF;` while counting and not `checksum &= 0XFFFF`. Also this is why it's important to add the words in reverse order. Adding them starting at the beginning can result in the carry bit being added at a different time:
```
same data, different order, different results
0xFFFF + 0x0001 (carry is now set) + 0x0000 = 0x0001
0x0000 + 0x0001 (carry is not set) + 0xFFFF (carry is now set but added next time) = 0x0000
```

You can download some .srm files and test your program. Try it with and without the carry flag, and doing it in reverse or forward direction and you should find the checksum off by 1 sometimes just to test it.

Good luck I'll keep and eye out for your editor!

**Comment by mcred** [comment]
Thanks for such an in depth reply @mikearnos! It was really helpful and I think I'm getting close. Here's what I have and most of my unit tests pass. Like you said, I had run into the checksum being off my 1 or a small handful.

```golang
func generateChecksum(g *Game) {
	for slot := 1; slot <= 3; slot ++ {
		var checksum uint = 0
		max := slot * 0xA00
		min := max - 0xA00
		for i := max-1; i >= min; i-- {
			if checksum > 0xFFFF {
				checksum -= 0xFFFF
			}
			if i % 2 == 0 {
				checksum += uint(g.GetValue(Attribute{i, true}))
			}
		}
		checksum &= 0xFFFF
		l := 0x1FF0 + ((slot - 1) * 2)
		g.SetValue(Attribute{l, true}, checksum)
	}
}
```

Some of my test cases still fail with being short by a handful of bits. Based of what I understand from your code and explanation:

*   Loop through each slot 1, 2, and 3
*   Zero out the checksum total and the carry bit
*   Set the range of each slot at 0xA00, multiply against each slot, subtract range to get starting block
*   Loop through each Byte in the Byte Array for the slot range
*   modulus 2 to get even blocks and get the 16bit Little Endian word for that block
*   Add to checksum total
*   If the checksum ever goes over 0xFFFF, subtract 0xFFFF from the checksum and set Carry bit value to 1
*   During the next checksum add, add the Carry bit and then set it to zero
*   At the end, convert to hex and save to proper location for the slot starting at 0x1FF0.

This get most of the unit test to pass, but I still have a few that are off:
```
GameSave_test.go:55: Checksum invalid: expected 33610, actual 33547
```
Sum values in the range of 16873-25819 seem to calculate without issue. It looks like when I'm in a low checksum or higher checksum value the above code starts to break down. 

I think I'm still missing a key part of the loop. Am I using the Carry Bit correctly? Anything about this process look out place or jump out at you?

**Comment by mikearnos** [comment]
Hey again. I'm not familiar with GoLang but it looks similar to C, at least in this simple example. I would try to set the variables first to keep the loop simple and easier to follow.
```
max := (slot * 0xA00) - 2
min := (slot - 1) * 0xA00
```

And for the loop I would just loop through by 2's and remove the modulo. By subtracting 1 each loop, you're running it twice as many times as needed, and I bet the `if checksum > 0xFFFF` is run multiple times because it's not within the modulo statement.

Notice the order, the `if checksum > 0xFFFF` being before the `checksum += ` is important. Change the order and you'll find some checksums are off a little. Just some little edge cases in this whole routine.
```
for i := max; i >= min; i -= 2 {
	if checksum > 0xFFFF {
		checksum -= 0xFFFF
	}
	checksum += uint(g.GetValue(Attribute{i, true}))
}
```

Try to keep some of those .srm files that you get wrong. It was frustrating seeing the checksums off by 1. But following the original assembly code closely gave the correct results.

**Comment by mcred** [comment]
Well, it looks like I had a faulty test. It had been working for a while thanks to your help! The code above actually works, but I did take your suggestions and clean it up. 

Thank you, again!

**Comment by mikearnos** [comment]
It sounds like you got it working properly. As another test, I put together this .srm file that tests some of the problems. The .sav files are individual save slots that can be rearranged and are easier to edit individually than as a whole .srm file. Combine with the footer.bin and fix the checksums and you have a clean .srm. Try it out. All three save slots should show up (but not playable). "No data" is a fail.

```
1 and 2 failed = out of bounds
1 and 3 failed = adding before carry
3 failed = adding from beginning not end
  or not handling carry properly &= 0xFFFF instead of -=0xFFFF
```

[CT srm file test.zip](https://github.com/mikearnos/snessum/files/4909166/CT.srm.file.test.zip)
